spring.application.name=ClusterManager
server.port=8080

cluster.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173

cluster.pseudo.cluster-id=local-lab
cluster.pseudo.tap-device-name=ClusterTap0
cluster.pseudo.cidr=10.77.0.0/24
cluster.pseudo.work-dir=run/pseudo-cluster
cluster.pseudo.auto-start=false
cluster.pseudo.java-executable=java
cluster.pseudo.health-timeout=5s
cluster.pseudo.tap.enabled=false
cluster.pseudo.tap.timeout=10s

cluster.rocketmq.cluster-id=rocketmq-demo
cluster.rocketmq.dashboard-name=JackLi
cluster.rocketmq.name-servers=192.168.50.78:9876

cluster.stream.publish-interval-ms=5000
